### ISSUE TITLE
Missing dependency for file that appears to be there

### ISSUE THREAD

**Issue by almo2001** [sureshjoshi/android-ndk-swig-example#1]
C:\Users\elarson\Desktop\Downloads\android-ndk-swig-example-master\NDKExample\app\src\main\jni\SeePlusPlus_wrap.cxx:802:1: fatal error: opening dependency

file C:\Users\elarson\Desktop\Downloads\android-ndk-swig-example-master\NDKExample\app\build\intermediates\ndk\debug\obj/local/arm64-v8a/objs/SeePlusPlus/C_\Users\elarson\Desktop\Downloads\android-ndk-swig-example-master\NDKExample\app\src\main\jni\SeePlusPlus_wrap.o.d: No such file or directory

Looking in the project hierarchy, I see app/c/SeePlusPlus_wrap.cxx, which got generated when I ran the SWIG commandline.

I looked down that whole absurd path, only to find that SeePlusPlus_wrap.o.d is in fact not there. I see NDKBug.o, NDKBug.o.d, SeePlusPlus.o and SeePlusPlus.o.d.

**Comment by sureshjoshi** [comment]
Hmm, very strange. One thing I've found is that sometimes there can be an issue with a long pathname. 

Please refer to http://www.sureshjoshi.com/mobile/android-ndk-in-android-studio-with-swig/ and a comment by Jakub. It seems to be similar.

**Comment by almo2001** [comment]
It looks like it's taking two file paths and concatenating them:

C:\Users\elarson\Desktop\Downloads\android-ndk-swig-example-master\NDKExample\ap‌​p\build\intermediates\ndk\debug\obj/local/arm64-v8a/objs/SeePlusPlus/

C_\Users\ela‌​rson\Desktop\Downloads\android-ndk-swig-example-master\NDKExample\app\src\main\jn‌​i\SeePlusPlus_wrap.o.d

I bet the intention is not to create a "C_" directory in the SeePlusPlus directory at the end of the first path.

**Comment by almo2001** [comment]
This seems to have to do with Windows given the Users directory special treatment.
I moved my project folder from 

C:\Users\elarson\Desktop\Downloads\android-ndk-swig-example-master

to

D:\Almo\Work\android-ndk-swig-example-master

And now it works.

**Comment by sureshjoshi** [comment]
Glad you got it sorted out. One point though, I don't know if it's the Users directory, as that's where I build all my Android apps from. Might be the total path length maybe? Either way, it's solved, and that's what matters.

Another thing is the path of the NDK directory. That might be extensive. On my systems, it was always c:\android-ndk or similar, so really slim path. I ran into issues on my Mac, where the path is buried as part of Xamarin, and thus really far down the directory hierarchy.

**Comment by almo2001** [comment]
My NDK path is also quite simple. It installed it by default into Program Files. Note the space: it kept telling me it didn't have the right version of GNU Make! :)

**Comment by almo2001** [comment]
Update... I just discovered that it started working, but is still concatenating the path:

D:\Almo\BinkSWIGTest2\NDKExample\app\build\intermediates\ndk\debug\obj\local\arm64-v8a\objs\SeePlusPlus\D_\Almo\BinkSWIGTest2\NDKExample\app\src\main\jni\SeePlusPlus_wrap.o.d

Exists. It's just that the filepath is short enough to work, it seems.

**Comment by Triodesabios** [comment]
Although it's too late now, I found a solution which worked for me for the same issue in another project:

1. Open a command prompt and run `subst J: path/to/your/project`.
2. Now you'll have created a virtual unit referencing only the project. You can open de project from unit J: instead. You'll be working with the real project but using a virtual path infinitely shorter.
3. To undo this action, run `subst J: /d` and that's it.

You can use any unit or path you wish instead of J:.
