### ISSUE TITLE
How to build with a library for linux

### ISSUE THREAD

**Issue by ares89** [sureshjoshi/android-ndk-swig-example#11]
I have a library which has four c++ header files and two .so files built for linux64, and I want to use it to run on android, how to configure the cmake file to achieve this? Could you make an example for this?Thank you!

**Comment by sureshjoshi** [comment]
Hey @ares89, so, in this case (if I understand correctly), you have some public headers for a compiled library? 

You'd need the libraries to be in the correct architectures for Android, if you want to use them... At least, that's how I understand it all to work. 

Here is an example of compiling the protocol buffer libraries for each of the Android architectures (https://github.com/sureshjoshi/mobile-protobuf-libs).  
    
    for target_arch in armeabi armeabi-v7a arm64-v8a x86 x86_64;

There's an even better example, that I haven't yet fully dug through, but essentially if you dig through TensorFlow's CMake files, they do a great job of building all libraries for all architectures - and will show you how it'll work.

So, you'll need to do similar to create libs for those architectures you're interested in.

**Comment by ares89** [comment]
Thanks for your reply!
I will dig your example and the tensorflow's, thank you!
