### ISSUE TITLE
Can find reference from external share library

### ISSUE THREAD

**Issue by cavarzan** [sureshjoshi/android-ndk-swig-example#17]
I'm trying to use a external `.so` library to generate the Wrappers.

After include the header `.h` file in the `SeePlusPlus.i` file, SWIG generate the classes but the build fails with errors:

```
android-ndk-swig-example/AS3/app/src/main/java/com/sureshjoshi/core/SeePlusPlusJAVA_wrap.cxx:7604: error: undefined reference to 'MapController::GetGridTotalColumns() const'

```

and at MapController:

```
class MapController
{
  public:
    MapController(void);
    ~MapController(void);
    ...
     static bool IsBridge(const line_t *p_line);
     uint16_t GetGridTotalColumns() const;
     ...
}
```

It seems that SWIG doesn't find the class reference. 

my `SeePlusPlus.i` file:

```
/* File : SeePlusPlus.i */
%module SeePlusPlus_Wrapper

/* Anything in the following section is added verbatim to the .cxx wrapper file */ 
%{
#include "GisCalculation.h"
#include "map_structs.h"
#include "MapController.h"
%}

/* This will allow us to iterate through arrays defined by STL containers */
%include "std_string.i"
%include "std_vector.i"

/* Create a template for std::vector< std::string > and std::vector< int > in Java */
namespace std {
   %template(IntVector) vector<int>;
   %template(StringVector) vector<string>;
}

/* This is the list of headers to be wrapped */
/* For Java, it seems we need the file of interest and all files up the inheritance tree */
%include "map_structs.h"
%include "GisCalculation.h"
%include "MapController.h"
```

**Comment by sureshjoshi** [comment]
Hi @cavarzan 

What's the inheritance tree look like? Is there any way to strip it down to JUST using the Map controller? 

Also, you said these are external .so files - so, I guess that means you have no implementation, but is the .so file linked correctly?

There isn't really enough information to debug very well.

**Comment by cavarzan** [comment]
@sureshjoshi thanks for the reply. The main goal is to use the MapController directly, without any custom implementation or bridge.
I'll push the code in a fork today to provide better info. Indeed the snippet is not very useful.

**Comment by cavarzan** [comment]
@sureshjoshi it's this fork:
https://github.com/cavarzan/android-ndk-swig-example

I have a libmapaccess.so, that points to `MapController.h`.

I'm trying to create the Java interfaces to access the functions declared in MapController.h and provided by libmapaccess.so.

After execute the `./gradlew externalNativeBuildDebug`, I got a several errors and the build fails:

Example: 
``` bash
android-ndk-swig-example/AS3/app/src/main/java/com/sureshjoshi/core/SeePlusPlusJAVA_wrap.cxx:4148: error: undefined reference to 'MapController::GetGridFirstItem() const'
```

it's inside AS3 project folder

**Comment by cavarzan** [comment]
@gmribas

**Comment by sureshjoshi** [comment]
Hi @cavarzan 

I haven't had a chance to launch AS and try it out, but just visually, I have a couple questions (apologies in advance if I misunderstand or missed anything).

You have a library that you want to expose via headers to Android. That shared library has no compilable code (.c files), which means your linkers have to become aware of the library directly (ie. matching header prototype declarations with definitions).

Questions:
* Was the .so file created using the Android NDK compiler?
* Do you have .so files for each Android architecture? 
* Have you made cmake aware that it needs to link to this new .so file? As in, does CMake know this library exists?

For example, if you wanted to pull C++ protocol buffers into Android (for lack of a better example).

I use this script to compile the protobuf library for Android: https://github.com/sureshjoshi/mobile-protobuf-libs/blob/master/generate-pb-libs.sh

That creates shared libraries for these architectures:

![jnilibs](https://user-images.githubusercontent.com/3823045/50306480-b7985d00-0463-11e9-9b0c-8a4f2cbe30c2.png)

In CMakeLists.txt, you then should have something similar to: 

    ... Typical CMakeLists stuff...

    add_library(protobuf-lite SHARED IMPORTED)
    set_target_properties(protobuf-lite PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libprotobuf-lite.so)

    target_link_libraries( # Specifies the target library.
                       SeePlusPlus

                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib}
                       protobuf-lite
                       )

        ... Typical CMakeLists stuff...

**Comment by sureshjoshi** [comment]
Also, please see issue #11

**Comment by gmribas** [comment]
@sureshjoshi I've made some changes on @cavarzan's fork.

The build succeeds, but mapacess is missing.
`UnsatisfiedLinkError: dlopen failed: library "libmapaccess.so" not found`

My changes:

added `lib/arm64-v8a/libmapaccess.so` and `lib/x86/libmapaccess.so`

**build.grade**
```
buildTypes {
        debug {
            ndk {
                abiFilters 'arm64-v8a', 'x86'
            }
        }
        release {
            ndk {
                abiFilters 'arm64-v8a', 'x86'
            }
            ...
        }
    }
```

**CmakeLists**
```
...

set(BINARY_DIR ${CMAKE_SOURCE_DIR}/src/main/cpp/lib)

add_library(mapaccess SHARED IMPORTED)
set_target_properties(mapaccess PROPERTIES IMPORTED_LOCATION ${BINARY_DIR}/${ANDROID_ABI}/libmapaccess.so)

# Specifies libraries CMake should link to your target library. You
# can link multiple libraries, such as libraries you define in this
# build script, prebuilt third-party libraries, or system libraries.
target_link_libraries( # Specifies the target library.
                       SeePlusPlus
                        mapaccess

                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib} )
```

**Comment by gmribas** [comment]
Placing `libmapaccess.so` also inside **jniLibs** fixes the packaging part.
But leads to a new error: `UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found`

**Comment by sureshjoshi** [comment]
@gmribas Did you create that shared object using the Android NDK? If so, which version? There have been a lot of changes in the NDK over the past year or so.

For example, I think back then, that shared library MAY have been bundled with the system by default (honestly, can't recall). 

However, according to https://developer.android.com/ndk/guides/cpp-support and https://developer.android.com/ndk/guides/standalone_toolchain - it says that libc++_shared.so must be bundled with the APK. So, maybe try that?

**Comment by gmribas** [comment]
@sureshjoshi thanks for the quick reply.
Adding this argument fixed it.

```
cmake {
    arguments '-DANDROID_STL=c++_shared'
}
```

**Comment by sureshjoshi** [comment]
@gmribas That code was already there though, no?
![screen shot 2018-12-21 at 16 30 11](https://user-images.githubusercontent.com/3823045/50364379-bf2c3480-053d-11e9-816a-ce9409f12329.png)

**Comment by gmribas** [comment]
Yes, it was.
I had removed it (I don't remember why anymore).

**Comment by sureshjoshi** [comment]
Roger, glad it works

**Comment by cavarzan** [comment]
@sureshjoshi thanks much!!!
