### ISSUE TITLE
Error: package com.sureshjoshi.core does not exist

### ISSUE THREAD

**Issue by lopspower** [sureshjoshi/android-ndk-swig-example#2]
I try to use NDK in Windows with Android Studio.
I think your project it's a very simple example to do that.
But now, I can't build your project (without any modification). In fact, it can't find the package name of jni files : 

error: package com.sureshjoshi.core does not exist
error: cannot find symbol class SeePlusPlus
error: cannot find symbol class IntVector
error: cannot find symbol class StringVector

Please help me !!

**Comment by sureshjoshi** [comment]
Hey @lopspower, have you read my associated blog post?

http://www.sureshjoshi.com/mobile/android-ndk-in-android-studio-with-swig/

Specifically, the 'Update' at the end with the following steps?
    
    cd ~/ 
    git clone https://github.com/sureshjoshi/android-ndk-swig-example.git
    [Open in Android Studio and let Gradle run and the project get indexed - this creates local.properties and the sdk.dir]
    cd android-ndk-swig-example/NDKExample
    ./gradlew runSwig
    (In Android Studio) Make Project

**Comment by lopspower** [comment]
Thank's @sureshjoshi but I find solution here : 
https://www.youtube.com/watch?v=okLKfxfbz40
