### ISSUE TITLE
Warning during build Current NDK support is deprecated

### ISSUE THREAD

**Issue by truedat101** [sureshjoshi/android-ndk-swig-example#3]
WARNING [Project: :app] Current NDK support is deprecated.  Alternative will be provided in the future.

Would be great to get this updated to latest gradle approach for NDK support

**Comment by sureshjoshi** [comment]
Yeah, I've seen that a bit - need to check what the latest approach is, I need to update my Android Studio - don't want to do that mid-project  :)

**Comment by truedat101** [comment]
The "state-of-the-art" for NDK building with gradle only took like 3 years ... I'm not sure where it's at right now.  Since this is the sole example of swig integration out there for Android, (other than the swig site), it would be cool to get this updated.  I'll have a look at what I find.

**Comment by truedat101** [comment]
In any case, I think gradle is the focus for this, and Android Studio is more of a choice that one makes (to IDE or not to IDE).

**Comment by sureshjoshi** [comment]
This is more of a not-fix. There is an alpha plugin, or the alternate route - in any case, it doesn't break anything.
