### ISSUE TITLE
native String runAndroidStudioNativeString() is not implemented

### ISSUE THREAD

**Issue by remgodow** [sureshjoshi/android-ndk-swig-example#4]
Develop branch builds correctly, however app crashes during launch on Android 4.4.2 due to java.lang.UnsatisfiedLinkError: Native method not found: com.sureshjoshi.android.ndkexample.MainActivity.runAndroidStudioNativeString:()Ljava/lang/String;

**Comment by sureshjoshi** [comment]
Thanks, will try to reproduce on mine Samsung S4 4.4.2

**Comment by sureshjoshi** [comment]
Hi @remgodow, I wasn't able to reproduce this on my 4.4.2... Are you able to get this working on other platforms? Or was it just missing a native method?

**Comment by remgodow** [comment]
It was just a missing native method implementation.
