### ISSUE TITLE
Gradle doesn't run itself

### ISSUE THREAD

**Issue by LudovicRansau** [sureshjoshi/android-ndk-swig-example#6]
Hello,

I'm a French student, and I tried to use **SWIG** with Android Studio by following your instructions:

[](url)https://github.com/sureshjoshi/android-ndk-swig-example

When I finished all those steps, I did not succeed to launch my Application, because there is no  possibly to run it (the run button is grayed out). So, I tried again to build this project following your instructions, and I found out that when I launch Android Studio after **git clone**, the gradle doesn't run by itself. Instead, a **Setup Sdk** link appears at the top right corner of the main window (see below)?

![setup_sdk](https://cloud.githubusercontent.com/assets/15090813/14952388/471b73f4-1060-11e6-953f-a9dfcec525e0.png)

When you state "let Gradle run", I assume that it's automatically started by Android Studio isn't it?

To try to understand the problem I compared a working Android Studio project with the result of your sample. As you can see below, there are quite a few differences about the color of the folders:

![screen_menu](https://cloud.githubusercontent.com/assets/15090813/14952317/b686e436-105f-11e6-9584-116ea7873ba8.png)

Sorry for my poor English and thank you very much in advance.

**Comment by sureshjoshi** [comment]
Hi, sorry, this got buried in my email.

Did you ever get it sorted out?

**Comment by dstd** [comment]
@LudovicRansau looks like you didn't succeed with `runSwig` step. The step `./gradlew runSwig` will build all required files into `com/sureshjoshi/core` folder. Sure, SWIG should be installed in your system.

That yellow bar is exactly about the step `this creates local.properties and the sdk.dir`. After that you have to go into terminal (a separate application or right here in Android Studio, the tab at the left bottom corner of your screenshot), and execute `./gradlew runSwift` command.

After that you will be able to start the app. Completed this quest by myself today 😄

**Comment by sureshjoshi** [comment]
Hi, this is no longer an issue in AS 2 or AS3
