### ISSUE TITLE
Android Studio 3.0  "error: package com.sureshjoshi.core does not exist"

### ISSUE THREAD

**Issue by MGasztold** [sureshjoshi/android-ndk-swig-example#8]
Hello,

I use latest Android Studio:

```
Android Studio 3.0
Build #AI-171.4408382, built on October 20, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1
```

and I am struggling with making the project AS3 work.

Below is a screenshot from the IDE with the errors:
![image](https://user-images.githubusercontent.com/11412357/32768605-c4a1eba6-c918-11e7-9daa-d283867e064e.png)

The only change in your files was updating gradle version in the top `build.gradle` line 10 to:

```
classpath 'com.android.tools.build:gradle:3.0.0'
```

originally it was `3.0.0-rc1` and Android Studio told me it is incompatibile. The sync was ok with my change.

I have swig installed (`swig` works in my command line).
I have Android NDK properly installed on my machine and path in `local.properties` is correct.

Could you give me any hint what I am doing wrong? Thanks in advance.

**Comment by sureshjoshi** [comment]
@MGasztold You might not be doing anything wrong - I've seen inconsistent results between myself and some of my colleagues with the exact same project(s). 

I'm in the process of updating my CMake files to see if I can make them a bit more consistent. Truthfully, I'm thinking about moving swig and such back to gradle, or, in my personal projects - I tend to use a bash script to call swig and then copy those files around, and then I source control those files.

It's definitely not a slick way to do it, but it's guaranteed to work  :)

**Comment by MGasztold** [comment]
Thank you for super fast response ! If I find any solution on my own I will share here.

**Comment by sureshjoshi** [comment]
Please do - sureshjoshi.core not existing means that after swig, the files weren't correctly copied from src/main/cpp/wrapper

And sometimes they're not deleted properly. I've tried a ton of permutations there, but nothing consistent.

One option could be re-specifying this line in CMAke:
set(CMAKE_SWIG_OUTDIR ${Project_SOURCE_DIR}/src/main/cpp/wrapper)

Change the outdir to exactly where the java code should be in the project... As you can see, later on I call "file(COPY ${JAVA_FILES} DESTINATION ${Project_SOURCE_DIR}/src/main/java/com/sureshjoshi/core)"

Which doesn't always work well. So, maybe just SWIG_OUTDIR to that directory?

The issue becomes where the SeePlusPlus_Wrapper.cxx file ends up, and making sure it gets compiled wherever it is (which might 'just work', I can't recall).

**Comment by MGasztold** [comment]
For me it seems that the SeePlusPlus_Wrapper files are not even created. 

I tried to manually run

```
swig -c++ -java -package com.sureshjoshi.core SeePlusPlus.i
```

inside `/src/main/cpp` directory and files were properly created:
![image](https://user-images.githubusercontent.com/11412357/32772642-ca788464-c926-11e7-9849-b6a11ce0e808.png)

When I comment copying files part in the `CMakeLists.txt` which is after the lines

```
swig_add_module(SeePlusPlus_Wrapper java ${Project_SOURCE_DIR}/src/main/cpp/SeePlusPlus.i)
swig_link_libraries(SeePlusPlus_Wrapper SeePlusPlus)
```

and hit sync gradle no files appear anywhere in the project tree. It's confusing.

**Comment by sureshjoshi** [comment]
Great catch!

That's so strange, as I seemed to be able to have a successful launch - even from a clean build. This is so strange. 

From the point you're at, I've noticed issues when re-building, that there will be a complaint of double of the identical java files, because for some reason Swig will run, but the copy/delete CMake commands don't run. Just a heads up.

I'm going to investigate this some more today, so I'll try to figure it out.

**Comment by MGasztold** [comment]
I confirm that:

- there are warnings about duplicate classes if wrapper directory is not removed
- the copy does not work, `core` java package appears where it should only if i use `set(CMAKE_SWIG_OUTDIR ${Project_SOURCE_DIR}/src/main/java/com/sureshjoshi/core)` in the `CMakeLists.txt`

**Comment by sureshjoshi** [comment]
Hmm... Okay, that's good to know. Also very strange - I wonder if I have some other things setup on my computer - as the copy does work... occasionally.

Can you do a PR with any of the fixes you've discovered?

**Comment by MGasztold** [comment]
Sure I can.

**Comment by MGasztold** [comment]
I decided to make a step back and be systematic. I tried to first find a gradle command that will generate the wrapper files for me from your CMakeLists.txt as is, without touching anything.

`./gradle externalNativeBuildDebug` did the job but somehow it is not doing the copy/delete part. The copy/delete happened after I hit default sync gradle in Android Studio afterwards.

After that project is buildable and working for me. So that's all I have to add in the end, no changes in the code of `CMakeLists.txt`. 

I think this is only the case when you are opening freshly cloned project.

**Comment by sureshjoshi** [comment]
Link references to this problem:

https://stackoverflow.com/questions/39260293/gradle-task-ordering-issue-in-android-studio/40014071#40014071

https://github.com/googlesamples/android-ndk/issues/284

**Comment by sureshjoshi** [comment]
@MGasztold Please try the latest. I've added a gradle hook to automatically run externalNativeBuild - seems to solve the problem. 

I've noticed that my Android Studio linter seems to be screwed up, as the generated directory is no longer being recognized as a valid java package (but if I rename it, it is...)

I've tried clean builds, refreshing my cache, and everything else - problem remains. I'm curious if you see it to. It doesn't prevent a build, just shows the red squiggles.

![screen shot 2017-11-15 at 03 38 28](https://user-images.githubusercontent.com/3823045/32827085-e4e224da-c9b8-11e7-9bbb-081cf64da98d.png)

**Comment by oldsa** [comment]
Yeah I also saw this same issue. Thanks for the renaming tip!

**Comment by bryanhatwood** [comment]
@sureshjoshi I was also getting the problem where the package isn't recognized by the IDE. It'll still run, but the red squiggles are all over my code. As a solution, delete the following line in AS3/app/app.iml (while AS is running):

`       <sourceFolder url="file://$MODULE_DIR$/src/main/java/com/sureshjoshi/core" isTestSource="false" />
`

The package should be recognized by AS and persists across AS restarts, cleans, rebuilds, etc. Curious to see if this works for you too.
